### PR TITLE
Add divergences

### PR DESCRIPTION
**Pull request by eigenfoo**

### CODE REVIEW

**Comment by ColCarroll** [comment]
The failures seem "serious" -- is everything getting marked as a divergence now? This *looks* right to me, but I can not figure out why the tests are so wrong.

You might add divergences to the `_slow` version, too?

**Comment by dfm** [comment]
I was just about to point out that "p_accept" bug :) Looks good to me now!

**Comment by ColCarroll** [comment]
Forgot to mention the required blog post, but that can be in a follow-up

**Comment by dfm** [comment]
Not sure you want to remove the "min" though...

**Comment by ColCarroll** [comment]
It looks like the "slow" version is not doing step size tuning, so I had left off the `min` since it is only a diagnostic for now. (the `min` is still in the fast version)

**Comment by dfm** [comment]
:+1:

**Pull request merged**
